
package ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2020-06-16T10:07:47.414-03:00
 * Generated source version: 3.2.2
 *
 */

public class CadenaCXFTwo_PortTypeServer{

    protected CadenaCXFTwo_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ws.CadenaCXFTwo();
        String address = "http://localhost:9090/CadenaCXFTwoPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new CadenaCXFTwo_PortTypeServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

