
package ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Fri Aug 07 19:53:22 ART 2020
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "health", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "health", namespace = "http://ws.das.edu.ubp.ar/")

public class Health {


}

