
package ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Mon Aug 05 18:56:04 ART 2019
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "sucursales", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sucursales", namespace = "http://ws.das.edu.ubp.ar/", propOrder = {"codigoentidadfederal", "localidad"})

public class Sucursales {

    @XmlElement(name = "codigoentidadfederal")
    private java.lang.String codigoentidadfederal;
    @XmlElement(name = "localidad")
    private java.lang.String localidad;

    public java.lang.String getCodigoentidadfederal() {
        return this.codigoentidadfederal;
    }

    public void setCodigoentidadfederal(java.lang.String newCodigoentidadfederal)  {
        this.codigoentidadfederal = newCodigoentidadfederal;
    }

    public java.lang.String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(java.lang.String newLocalidad)  {
        this.localidad = newLocalidad;
    }

}

