INSERT INTO ingrediente (idIngrediente, nombreIngrediente)
VALUES
 (1, 'Pan de Hamburguesa')
,(2, 'Pan de Pancho')
,(3, 'Galletita Saladas')
,(4, 'Galletitas Dulces')
,(5, 'Arroz Blanco')
,(6, 'Pechuga Pollo')
,(7, 'Leche')
,(8, 'Harina de Trigo 000')
,(9, 'Huevo')
,(10, 'Crema de Leche')
,(11, 'Queso Rallado')
,(12, 'Aceite de Girasol')
,(13, 'Aji Molido')
,(14, 'Sal Fina')
,(15, 'Pimienta Negra Molida')
,(16, 'Cebolla')
,(17, 'Zanahoria')
,(18, 'Perejil Deshidratado')
,(19, 'Pimienta Blanca Molida')
,(20, 'Oregano')
,(21, 'Poroto Alubia')
,(22, 'Arveja Seca')
,(23, 'Ajo Deshidratado')
,(24, 'Tomate Pelado')
,(25, 'Garbanzo Seco')
,(26, 'Limon')
,(27, 'Sesamo')
,(28, 'Caldo Para Verduras')
,(29, 'Comino Molido')
,(30, 'Pimenton')
,(31, 'Tallarines')
,(32, 'Jamon Cocido')
,(33, 'Margarina')
,(34, 'Bistec')
,(35, 'Atun En Lomitos')
,(36, 'Pan Rallado')
,(37, 'Ricota')
,(38, 'Espinaca')
,(39, 'Berenjena')
,(40, 'Provenzal')
,(41, 'Queso Cremoso')
,(42, 'Vinagre')
,(43, 'Zapallo')
,(44, 'Carne Molida')
,(45, 'Queso Dambo')
,(46, 'Tapa de Empanada')
,(47, 'Pimiento Rojo')
,(48, 'Pata Pollo')
,(49, 'Vino Blanco')
,(50, 'Papa blanca')
,(51, 'Salsa Cesar')
,(52, 'Lechuga')
,(53, 'Pan Lacteado')
,(54, 'Brocoli')
,(55, 'Bola de Lomo')
,(56, 'Choclo')
,(57,'Caldo Para Carne')
,(58, 'Acelga')
,(59,'Apio')
,(60,'Lenteja')
,(61,'Vino Tinto')
,(62,'Laurel')
,(63,'Tomillo')
,(64,'Albahaca')
,(65,'Agua')
,(66,'Cebolla Verdeo')
,(67, 'Aceituna')
,(68,'Sal Gruesa')
,(69,'Harina de Trigo 0000')
,(70,'Nuez Moscada')
,(71,'Queso Mozzarella')
,(72,'Colita de Cuadril')
,(73,'Mostaza')
,(74,'Romero')
,(75,'Puerro')
,(76,'Solomillo')
,(77,'Vino Oporto')
,(78,'Manzana')
,(79,'Filet de Merluza')













