INSERT INTO  provincia (idProvincia, codigoEntidadFederal,nombreProvincia)
VALUES
 (1 ,'AR-A','Salta')
,(2 ,'AR-B','Provincia de Buenos Aires')
,(3 ,'AR-C','Capital Federal')
,(4 ,'AR-D','San Luis')
,(5 ,'AR-E','Entre Ríos')
,(6 ,'AR-F','La Rioja')
,(7 ,'AR-G','Santiago del Estero')
,(8 ,'AR-H','Chaco')
,(9 ,'AR-J','San Juan')
,(10 ,'AR-K','Catamarca')
,(11 ,'AR-L','La Pampa')
,(12 ,'AR-M','Mendoza')
,(13 ,'AR-N','Misiones')
,(14 ,'AR-P','Formosa')
,(15 ,'AR-Q','Neuquén')
,(16 ,'AR-R','Río Negro')
,(17 ,'AR-S','Santa Fe')
,(18 ,'AR-T','Tucumán')
,(19 ,'AR-U','Chubut')
,(20 ,'AR-V','Tierra del Fuego')
,(21 ,'AR-W','Corrientes')
,(22 ,'AR-X','Córdoba')
,(23 ,'AR-Y','Jujuy')
,(24 ,'AR-Z','Santa Cruz')